[package]
name = "oraiswap-token"
version = "0.2.0"
authors = ["Terraform Labs, PTE."]
edition = "2018"
description = "Backward compatible implementation of a CosmWasm-20 compliant token"
license = "MIT"
repository = "https://github.com/oraiswap/oraiswap"
homepage = "https://cosmwasm.com"
documentation = "https://docs.cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all init/handle/query exports
library = []

[dependencies]
cw0 = { version = "0.5.0" }
cw2 = { version = "0.5.0" }
cw20 = { version = "0.5.0" }
# using cw20-base contract as library
cw20-base = { version = "0.5.0", features = ["library"] }
cosmwasm-std = { version = "0.13.2" }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.21" }
oraiswap = { path = "../../packages/oraiswap" }

[dev-dependencies]
# we only need to enable this if we use integration tests
cosmwasm-schema = { version = "0.13.2" }
cosmwasm-storage = { version = "0.13.2" }
